import type { Book, User } from '@/lib/types';

export const mockUser: User = {
  uid: 'user-123',
  firstName: 'Jane',
  lastName: 'Doe',
  mobileNumber: '+11234567890',
  contactInfo: 'jane.doe@example.com',
  profilePicUrl: 'https://picsum.photos/seed/user/100/100',
};

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    genre: 'Fantasy',
    description: "A novel about a library that contains an infinite number of books, each one the story of another reality.",
    condition: 'used-good',
    originalPrice: 26.0,
    sellingPrice: 13.5,
    sellerId: 'user-456',
    sellerName: 'John Smith',
    sellerContact: '555-1234',
    bookImageUrl: 'https://picsum.photos/seed/book1/400/600',
  },
  {
    id: '2',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    genre: 'Sci-Fi',
    description: "A lone astronaut must save the earth from a disaster in this thrilling sci-fi adventure.",
    condition: 'new',
    originalPrice: 28.0,
    sellingPrice: 20.0,
    sellerId: 'user-789',
    sellerName: 'Emily Jones',
    sellerContact: 'emily@email.com',
    bookImageUrl: 'https://picsum.photos/seed/book2/400/600',
  },
  {
    id: '3',
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    genre: 'Sci-Fi',
    description: "A story about Klara, an Artificial Friend with outstanding observational qualities, who watches the behavior of those who come in to browse.",
    condition: 'used-fair',
    originalPrice: 20.0,
    sellingPrice: 8.0,
    sellerId: 'user-101',
    sellerName: 'Michael Brown',
    sellerContact: 'Call 555-5678',
    bookImageUrl: 'https://picsum.photos/seed/book3/400/600',
  },
  {
    id: '4',
    title: 'The Four Winds',
    author: 'Kristin Hannah',
    genre: 'Historical Fiction',
    description: "An epic novel of love and heroism and hope, set during the Great Depression, a time when the country was in crisis and at war with itself.",
    condition: 'used-good',
    originalPrice: 30.0,
    sellingPrice: 15.0,
    sellerId: 'user-456',
    sellerName: 'John Smith',
    sellerContact: '555-1234',
    bookImageUrl: 'https://picsum.photos/seed/book4/400/600',
  },
  {
    id: '5',
    title: 'Circe',
    author: 'Madeline Miller',
    genre: 'Fantasy',
    description: 'A thrilling, feminist retelling of the Greek myth of Circe, the goddess of magic.',
    condition: 'new',
    originalPrice: 16.99,
    sellingPrice: 12.0,
    sellerId: 'user-112',
    sellerName: 'Sarah Davis',
    sellerContact: 'sarah.d@web.com',
    bookImageUrl: 'https://picsum.photos/seed/book5/400/600',
  },
  {
    id: '6',
    title: 'Educated: A Memoir',
    author: 'Tara Westover',
    genre: 'Biography',
    description: 'An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    condition: 'used-good',
    originalPrice: 28.00,
    sellingPrice: 10.0,
    sellerId: 'user-789',
    sellerName: 'Emily Jones',
    sellerContact: 'emily@email.com',
    bookImageUrl: 'https://picsum.photos/seed/book6/400/600',
  },
  {
    id: '7',
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'Sci-Fi',
    description: "Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Muad'Dib.",
    condition: 'used-fair',
    originalPrice: 18.00,
    sellingPrice: 7.50,
    sellerId: 'user-101',
    sellerName: 'Michael Brown',
    sellerContact: 'Call 555-5678',
    bookImageUrl: 'https://picsum.photos/seed/book7/400/600',
  },
  {
    id: '8',
    title: 'Atomic Habits',
    author: 'James Clear',
    genre: 'Self-Help',
    description: 'An easy and proven way to build good habits and break bad ones.',
    condition: 'new',
    originalPrice: 27.00,
    sellingPrice: 18.00,
    sellerId: 'user-112',
    sellerName: 'Sarah Davis',
    sellerContact: 'sarah.d@web.com',
    bookImageUrl: 'https://picsum.photos/seed/book8/400/600',
  },
];
